GET http://localhost:8080/Thuzoi/php/SQL/do_an/api/sach/index.php
Content-Type: application/json

####

POST http://localhost:8080/Thuzoi/php/SQL/do_an/api/sach/index.php
Content-Type: application/json

{
    "ten_sach":"test",
    "id_tac_gia":1,
    "gioi_thieu":"<div>Noi dung gioi thieu.</div>",
    "doc_thu":"test.html",
    "id_loai_sach":2,
    "id_nha_xuat_ban":3,
    "so_trang":100,
    "ngay_xuat_ban":"2020-11",
    "kich_thuoc":"200cm x 200cm",
    "trong_luong":"200",
    "sku":"adsadfddgf",
    "trang_thai":1,
    "hinh":"test.jpg",
    "don_gia":"50000",
    "gia_bia":"60000",
    "noi_bat":0
}

####

PUT http://localhost:8080/Thuzoi/php/SQL/do_an/api/sach/index.php
Content-Type: application/json

{
    "ten_sach":"test 123",
    "id_tac_gia":1,
    "gioi_thieu":"<div>Noi dung gioi thieu.</div>",
    "doc_thu":"test.html",
    "id_loai_sach":2,
    "id_nha_xuat_ban":3,
    "so_trang":100,
    "ngay_xuat_ban":"2020-11",
    "kich_thuoc":"200cm x 200cm",
    "trong_luong":"200",
    "sku":"adsadfddgf",
    "trang_thai":1,
    "hinh":"test.jpg",
    "don_gia":"50000",
    "gia_bia":"60000",
    "noi_bat":0,
    "id_cap_nhat":97
}

####

DELETE http://localhost:8080/Thuzoi/php/SQL/do_an/api/sach/index.php
Content-Type: application/json

{
    "id_xoa":96
}

####
GET http://localhost:8080/Thuzoi/php/SQL/do_an/api/auth/index.php
Content-Type: application/json

{
    "tai_khoan":"admin",
    "mat_khau":"123456"
}